# Generated by Django 3.1 on 2020-08-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowsay',
            name='text',
            field=models.CharField(max_length=80),
        ),
    ]
